### ISSUE TITLE
Item Page 반환 API

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#101]
## 🌳 진행할 작업
- page 숫자와 지역을 Get요청받아 Item page 를 반환하는 API 개발

## 🌱 TODO
- [x]  entity 정의
- [x] API 초안 구현
- [ ] 유효성 검사 추가
- [x] 단위 테스트 추가
- [x] API 문서 수정

## 기타
- 아직 없음
