### ISSUE TITLE
일반 로그인, 회원가입 기능 구현

### ISSUE THREAD

**Issue by bread1022** [masters2023-2nd-project-05/second-hand#112]
## 🌳 진행할 작업
- 아이디의 중복을 확인하고, 일반 회원의 로그인과 회원가입 기능을 구현합니다.

## 🌱 TODO
- [x] 회원가입 레이아웃 생성
- [x] 아이디 중복확인 후 로그인
- [x] 아이디 중복확인 후 회원가입
- [x] 유저 프로필 등록
- [x] 파일 첨부 컴포넌트 구현 `FileInput`

## 기타
- file upload (fileReader)
- createPortal
