### ISSUE TITLE
상품 상세 페이지 구현

### ISSUE THREAD

**Issue by ahnlook** [masters2023-2nd-project-05/second-hand#134]
## 🌳 진행할 작업
- 홈에서 상품을 클릭 시 이동하는 상품 상세 페이지 구현

## 🌱 TODO
- [x]  상품 상세페이지 UI
- [x] 카테고리명 표시
- [x] 이미지 캐러셀
- [x] 상품 상태 변경
- [x] 좋아요 on / off
- [x] 채팅방으로 이동
