### ISSUE TITLE
필터된 상품 목록 API

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#149]
## 🌳 진행할 작업
- 필터된 상품 목록 API 작업

## 🌱 TODO
- [ ] QueryDSL 초기 설정
- [ ]  사용자는 자신이 판매중인/판매완료한 상품 목록을 볼 수 있다
- [ ]  사용자는 자신의 동네의 상품 목록을 특정 카테고리별로 볼 수 있다.
- [ ] 사용자는 자신의 동네의 상품 목록을 볼 수 있다. #101  

## Refs.
- #101
