### ISSUE TITLE
상품 판매 상태 변경, 삭제 API

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#171]
## 🌳 진행할 작업
- 판매자는 상품 판매 상태만 별도로 수정할 수 있다.
- 판매자는 판매중인 판매 상품 목록에서 글을 삭제할 수 있다.

## 🌱 TODO
- [ ] 판매자는 상품 판매 상태만 별도로 수정할 수 있다.
- [ ] 판매자는 판매중인 판매 상품 목록에서 글을 삭제할 수 있다.
- [x] 각 테이블에 `isDelete` 컬럼 추가
