### ISSUE TITLE
채팅방 UI 구현

### ISSUE THREAD

**Issue by ahnlook** [masters2023-2nd-project-05/second-hand#230]
## 🌱 TODO
- [ ] 상품 이미지 표시
- [ ] 상품 타이틀 표시
- [ ] 상품 가격 표시
- [ ] 상대가 보낸 메시지
- [ ] 내가 보낸 메시지
- [ ] 팝업 시트 (알람끄기, 신고하기, 채팅방 나가기)
