### ISSUE TITLE
채팅 WS API 구현

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#280]
## 🌳 진행할 작업
- 채팅 WS 프로토콜에 대한 API를 구현한다.

## 🌱 TODO
- [ ] 사용자는 채팅방을 나갈 수 있다.
- [ ] 사용자는 채팅 메시지를 보낼 수 있다.
    - [x] #281
    - [ ] 사용자가 보낸 채팅 메시지가 NoSQL에 저장된다.
- [ ] 사용자는 채팅 메시지를 받을 수 있다.
- [ ] 사용자는 채팅방에 상대방이 존재하는지 알 수 있다.

## Refs.
- #260 

### Tests.
- #249 
- #197
