### ISSUE TITLE
상품 상세 내용, 파일 수정 기능 구현

### ISSUE THREAD

**Issue by bread1022** [masters2023-2nd-project-05/second-hand#305]
## 🌳 진행할 작업
- 상품 상세 내용, 파일 수정 기능 구현

## 🌱 TODO
- [x] 상품 상세화면에서 수정 버튼을 클릭하여 수정 초기값 표시
- [x] 상품 사진 수정 기능, POST 요청
- [x] 상품 사진 + 내용 수정,  PUT 요청
