### ISSUE TITLE
Debugging & Refactoring

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#390]
## 🌳 진행할 작업
- 디버깅
- 예외처리 추가
- 리팩토링
- 테스트 추가

## 🌱 TODO
- [x] SSE 중복 헤더 수정
- [x] 채팅 로그가 없는 경우 예외처리  
- [x] 예외 수정
- [x] validation exception global handler 추가
- [x] #415
