### ISSUE TITLE
전반적인 에러 해결

### ISSUE THREAD

**Issue by jaea-kim** [masters2023-2nd-project-05/second-hand#418]
## 🌳 진행할 작업
- FE & iOS 가 요청한 에러 해결

## 🌱 TODO
- [x]  판매내역 조회 시 에러
- [x] `/chats/items/{itemId}`  조회 시 500번 에러
- [x] `/chats?page=0` 조회 시 updateAt, lastUpdate 값이 현재 시간과 같음 문제
- [ ] 테스트 코드 추가
- [x] #466 
- [x] #438
