### ISSUE TITLE
채팅 메시지 알람 Emitter complete 처리 디버깅

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#474]
## 🌳 진행할 작업
- 채팅 메시지 알람시 emitter가 complete되었는데도 계속 해당 에밋으로 요청을 시도하는 문제 해결

## 🌱 TODO
- [x] sse emitter 서버 로깅 추가
- [x] sse 자료구조 redis로 리팩토링 -> 취소
- [x] sse repository 테스트
- [ ] sse service 테스트

## 기타
- 목표 해결 일정 ~ 12.4 월요일

**Comment by new-pow** [comment]
@ahnlook 
Timeout 에러시 Emitter가 complete되도록 처리하였습니다.
Emitter가 complete되면 새로 SSE구독 요청 보내주시면 될 것 같은데 로직 어떻게 생각하세요?

**Comment by ahnlook** [comment]
> @ahnlook Timeout 에러시 Emitter가 complete되도록 처리하였습니다. Emitter가 complete되면 새로 SSE구독 요청 보내주시면 될 것 같은데 로직 어떻게 생각하세요?

그럼 Emitter가 complete 되었을 때 클라에서 어떻게 알 수 있게 되는 건가요? 그리고 새로 SSE 구독 요청을 보낸다는 의미는, 기존 SSE 구독 요청과는 다를까요?
