### ISSUE TITLE
새로운 채팅방 알림 서비스 기획

### ISSUE THREAD

**Issue by new-pow** [masters2023-2nd-project-05/second-hand#475]
## 🌳 진행할 작업
- 현재의 SSE 알람은 기존 채팅방에서만 적용되는 문제
- 새로운 채팅방이 생성되었을 때도 알림을 줘야하는 상황

## 🌱 TODO
- [x] 서비스 로직 흐름 정리
- [x] 새로운 채팅방 알림 서비스 구현
- [ ] 새로운 채팅방 알림 서비스 테스트
- [x] 배포 테스트

## 기타
- 목표 종료 기간은 12월 4일 논의 후 추가 예정

**Comment by new-pow** [comment]
## 결정 내용
- 새로운 채팅방과 메시지가 발생하였을 때 다음과 같은 포맷으로 SSE 알람 발행
- 응답 타입을 추가하여 새 메시지와 새로운 채팅방을 구분할 수 있을 것 같은데, 이것은 구현하면서 해결

```json
data: {
                "chatroomId": "bc21f206-4005-11ee-869c-0242ac110002",
                "opponent": {
                    "memberId": "dewey",
                    "profileImgUrl": "https://ca.slack-edge.com/T74H5245A-U04FXMJ80BY-6ec5d36e2615-512"
                },
                "item": {
                    "itemId": 3,
                    "title": "제발.. 수정ㅜㅓ수ㅇㅜㅓ수저정",
                    "thumbnailImgUrl": "https://secondhand-team5-bucket.s3.ap-northeast-2.amazonaws.com/thumbnails/e9b29082-7d0e-4f5b-93bc-34200ab08321-image0.jpeg"
                },
                "chatLogs": {
                    "lastMessage": "", //채팅 내역
                    "updateAt": datetime,
                    "unReadCount": 0
                }
            }
```

**Comment by new-pow** [comment]
@ahnlook 새로운 채팅방이 생성되면 다음과 같은 메시지가 전달됩니다.
```
 ChatroomDetails(
   chatroomId=4b1bf265-2334-4d44-87c0-765d087461fc,
   opponentId=guestaccount,
   isOpponentIn=true, item= (
          itemId;
          title;
          price;
          thumbnailImgUrl;
          Status status;
          isDelete;
   )
)
```

이후 채팅 메시지가 도착합니다.
채팅 생성이 먼저 진행되고 별도 요청으로 메시지가 전달되므로 따로따로 보내드려야 할거같아요 🥲
혹시 수정이 필요한 사항있으면 이슈로 남겨주십시오.
