### ISSUE TITLE
채팅방 메타정보 캐시로 저장

### ISSUE THREAD

**Issue by jaea-kim** [masters2023-2nd-project-05/second-hand#480]
## 🌳 진행할 작업
- 채팅방 메타정보 캐시 저장 로직 구현
## 🌱 TODO
- [x] 채팅방 생성 시
- [x] 채팅방 접속 시(캐시 존재)
- [x] 채팅방 캐시 삭제 후 접속 시
- [ ] 채팅방에서 접속하지 않을 시
- [ ] 채팅방 완전 삭제 시
- [ ] 채팅방에 새로운 메시지 도착 시
- [ ] 채팅방에 새로운 메시지 보낼 시
## 기타
- #466
