### ISSUE TITLE
oAuth 로 로그인 하기 & 일반회원 로그인 하기 

### ISSUE THREAD

**Issue by jaea-kim** [masters2023-2nd-project-05/second-hand#81]
## 🌳 진행할 작업
- oAuth로 로그인 하기 로직 변경

> - 200 OK : 로그인 성공
> - 401 Unauthorized : 가입되지 않은 회원, 회원가입 하도록 깃허브 유저 정보 보내줌

- 로그인 성공시 jwt 토큰 생성해서 헤더에 담아 보내주기 

## 🌱 TODO
- [ ] oAuth 로그인 로직 수정
- [ ] 401 에러 반환, 유저 정보 담아서 
- [ ] jwt 토큰 생성 
- [ ] jwt 토큰 헤더에 담아 보내기  

## 기타
- 기타 설명
